### ISSUE TITLE
intelligence limitation

### ISSUE THREAD

**Issue by alexandremsouza1** [zeyu2001/chess-ai#2]
froze on that screen

![Screenshot_20201221-203832](https://user-images.githubusercontent.com/38253342/102832287-b5f42d80-43cc-11eb-9493-a13d8224de84.png)

**Comment by zeyu2001** [comment]
See the 'Status' section: a draw is detected due to [threefold repetition](https://en.wikipedia.org/wiki/Threefold_repetition).
However, it would be great to modify the AI to avoid draws. I'll see what I can do.

**Comment by zeyu2001** [comment]
With 30e96db3b77495ea462c5d9990fc375ba5a1ae7e and 35a656807ca74911c458c4abc1557e06e37f9281, the AI will now check for draws and win conditions.
